GTA04 rootfs: test scripts for modem prepared to distinguish between GTM601 and PHS8/PLS8
Signed-off-by: H. Nikolaus Schaller <hns@goldelico.com>

diff --git a/GTA04/root/wwan b/GTA04/root/wwan
--- a/GTA04/root/wwan
+++ b/GTA04/root/wwan
@@ -4,24 +4,19 @@
 # usage: wwan
 #
 
+APN="$(cat wwan.conf)"
+
 rfkill unblock wwan
 sleep 5
 
 make femtocom
 
-for i in $(cd /sys/class/tty/ && echo ttyHS*)
-	do
-	if [ "$(cat /sys/class/tty/$i/hsotype)" == "Application" ]
-		then
-		IF="/dev/$i"
-	fi
-done
+case $(cat /proc/device-tree/model) in
+Neo900 | Pyra-Handheld ) # device with Cinterion
+	sleep 8
+	IF="/dev/ttyACM0"
 
-[ "$IF" ] || (echo HSO Application interface not found; exit 1)
-
-echo Interface: $IF
-
-APN="$(cat wwan.conf)"
+[ -r "$IF" ] || (echo Modem Application interface not found; exit 1)
 
 (
 echo "AT_OPONI=1"; sleep 1	# report current network registration
@@ -59,3 +54,60 @@ echo "AT_OWANNWERROR?"; sleep 1	# finally check for error
 		fi
 	done
 echo "Could not set up"
+	;;
+
+* ) # GTA04 with OPTION GTM601W
+	sleep 5
+for i in $(cd /sys/class/tty/ && echo ttyHS*)
+	do
+	if [ "$(cat /sys/class/tty/$i/hsotype)" == "Application" ]
+		then
+		IF="/dev/$i"
+	fi
+done
+
+[ "$IF" ] || (echo HSO Application interface not found; exit 1)
+
+echo Interface: $IF
+
+(
+echo "AT_OPONI=1"; sleep 1	# report current network registration
+echo "AT_OSQI=1"; sleep 1	# report signal quality in dBm
+echo "AT_OEANT=1"; sleep 1	# report quality level (0..4 or 5)
+echo "AT_OCTI=1"; sleep 1	# report GSM/GPRS/EDGE cell data rate
+echo "AT_OUWCTI=1"; sleep 1	# report available cell data rate
+echo "AT_OUHCIP=1"; sleep 1	# report HSDPA call in progress
+echo "AT_OSSYS=1"; sleep 1	# report system (GSM / UTRAN)
+echo "AT_OPSYS=5,3"; sleep 1	# connect any system
+echo "AT_OWANCALLUNSOL=1"; sleep 1	# report _OWANCALL: on this tty
+echo "AT+CGDCONT=1,\"IP\",\"$APN\""; sleep 1	# set APN
+echo "AT_OWANCALL=1,1,1"; sleep 1	# start call
+echo "AT_OWANNWERROR?"; sleep 30	# give some time to establish registration
+echo "AT_OWANDATA?"; sleep 60	# should have connected - ask for network data
+echo "AT_OWANNWERROR?"; sleep 1	# finally check for error
+) | ./femtocom $IF | while read MSG C IP GW DNS1 DNS2 NBNS1 NBNS2 SPEED MORE
+	do
+	echo $MSG $C $IP $GW $DNS1 $DNS2 $NBNS1 $NBNS2 $SPEED $MORE
+	if [ "$MSG" == "_OWANDATA:" ] # _OWANDATA: 1, 10.152.124.183, 0.0.0.0, 193.189.244.225, 193.189.244.206, 0.0.0.0, 0.0.0.0,144000
+		then
+		IP=$(expr "$IP" : "\(.*\),")
+		DNS1=$(expr "$DNS1" : "\(.*\),")
+		DNS2=$(expr "$DNS2" : "\(.*\),")
+		ifconfig hso0 $IP netmask 255.255.255.255 up
+		# FIXME: this overwrites the DNS used for e.g. USB connection!
+		echo "nameserver $DNS1" >/etc/resolv.conf
+		echo "nameserver $DNS2" >>/etc/resolv.conf
+		echo "Setup done"
+		# forward all IP traffic (even if it arrives from the USB host) through WWAN
+		route add default dev hso0
+		echo 1 >/proc/sys/net/ipv4/ip_forward
+		iptables -t nat -A POSTROUTING -o hso0 -j MASQUERADE
+		exit 0
+		fi
+	done
+echo "Could not set up"
+	;;
+esac
+
+
+exit
diff --git a/GTA04/root/wwan-status b/GTA04/root/wwan-status
--- a/GTA04/root/wwan-status
+++ b/GTA04/root/wwan-status
@@ -9,6 +9,47 @@ sleep 5
 
 make femtocom
 
+case $(cat /proc/device-tree/model) in
+Neo900 | Pyra-Handheld ) # device with Cinterion
+	sleep 8
+	# lsusb | fgrep -q "ID 1e2d:0054" || {echo No Modem found; exit 1}
+	IF="/dev/ttyACM0"	# PHS8 in at^sdata=6 mode
+	if ! [ -r "$IF" ]
+	then # PHS8 might be in at^sdata=3 mode (NEVER SWITCH TO at^sdata=2 or you are in big trouble!)
+		modprobe usbserial
+		echo 1e2d 0053 >/sys/bus/usb-serial/drivers/generic/new_id
+		sleep 1
+		IF="/dev/ttyUSB3" # try alternate
+	fi
+
+	[ -r "$IF" ] || {echo Modem Application interface not found; exit 1}
+
+	echo Interface: $IF
+
+	(
+	# FIXME
+	echo "AT^SBV"; sleep 1
+	echo "AT^SDATA?"; sleep 1
+#echo "AT\$QCSIMSTAT?"; sleep 1
+	echo "AT+CGMI"; sleep 1
+	echo "AT+CGMM"; sleep 1
+	echo "AT+CGSN"; sleep 1
+	echo "AT+CIMI"; sleep 1
+	echo "AT+CPIN?"; sleep 1
+	echo "AT+CSQ"; sleep 1
+#echo "AT_OLCC=1"; sleep 1
+#echo "AT_OSQI=1"; sleep 1
+#echo "AT_OWANCALL?"; sleep 1
+#echo "AT_OWANDATA?"; sleep 1
+#echo "AT_OWANNWERROR?"; sleep 1
+	echo "AT^SMONI"; sleep 1	# serving cell
+	echo "AT^SMONP"; sleep 1	# neighbour cell
+	sleep 60
+	) | ./femtocom $IF
+	;;
+
+* ) # GTA04 with OPTION GTM601W
+	sleep 5
 for i in $(cd /sys/class/tty/ && echo ttyHS*)
 	do
 	if [ "$(cat /sys/class/tty/$i/hsotype)" == "Application" ]
@@ -38,3 +79,8 @@ echo "AT_OWANNWERROR?"; sleep 1
 echo "AT_ONCI?"; sleep 1
 sleep 60
 ) | ./femtocom $IF
+	;;
+esac
+
+
+exit
