Letux: Rootfs: gps-on: improve message for GTA04 with broken GPS chip/driver; extend sleep for programming the PxS8
Signed-off-by: H. Nikolaus Schaller <hns@goldelico.com>

diff --git a/Letux/root/gps-on b/Letux/root/gps-on
--- a/Letux/root/gps-on
+++ b/Letux/root/gps-on
@@ -29,7 +29,9 @@ case "$IF" in
 		;;
 
 	/dev/ttyHS* ) # GTA04 with OPTION GTM601W
-		echo /dev/ttyO1
+		echo GTA04 with broken GPS chip >&2
+		echo /dev/ttyHS_Application
+		exit 1
 		;;
 
 	/dev/ttyACM0 )
@@ -46,23 +48,22 @@ case "$IF" in
 	/dev/ttyACM1 )	# PLS8
 		(
 		# note: * commands report "+CME ERROR: operation failed" if the setting is already done
-		echo 'AT^SGPSC="Engine","0"'; sleep 0.2		# must turn off before enabling GLONASS
-		echo 'AT^SGPSC="Nmea/Glonass","on"'; sleep 0.2	# * enable GLONASS
-		echo 'AT^SGPSC="Engine","1"'; sleep 0.2		# enable GPS
-		echo 'AT^SGPSC="Nmea/Freq",1'; sleep 0.2		# once a second
-		echo 'AT^SGPSC="Nmea/Output","on"'; sleep 0.2		# enable data stream
-		echo 'AT^SGPSC="Nmea/Urc","on"'; sleep 0.2		# unsolicited reports
-		echo 'AT^SGPSC="Power/Antenna","auto"'; sleep 0.2	# * switch LNA to auto mode
+		echo 'AT^SGPSC="Engine","0"'; sleep 0.4		# must turn off before enabling GLONASS
+		echo 'AT^SGPSC="Nmea/Glonass","on"'; sleep 0.4	# * enable GLONASS
+		echo 'AT^SGPSC="Engine","1"'; sleep 0.4		# enable GPS
+		echo 'AT^SGPSC="Nmea/Freq",1'; sleep 0.4		# once a second
+		echo 'AT^SGPSC="Nmea/Output","on"'; sleep 0.4		# enable data stream
+		echo 'AT^SGPSC="Nmea/Urc","on"'; sleep 0.4		# unsolicited reports
+		echo 'AT^SGPSC="Power/Antenna","auto"'; sleep 0.4	# switch LNA to auto mode - will report +CME ERROR if already in auto mode
 		) | /root/femtocom $IF >&2 &
 		echo /dev/ttyACM2
 		;;
 
 	/dev/ttyUSB[0-4] )	# PHS8 in mutiplexed mode
 		(
-		echo 'AT^SGPSC="Engine","1"'; sleep 0.2		# enable GPS
-		echo 'AT^SGPSC="Nmea/Output","on"'; sleep 0.2		# normal output
-		echo 'AT^SGPSC="Power/Antenna","on"'; sleep 0.2	# turn on LNA
-		echo 'AT^SGPSC="Power/Antenna","auto"'; sleep 0.2	# switch to auto mode
+		echo 'AT^SGPSC="Engine","1"'; sleep 0.4		# enable GPS
+		echo 'AT^SGPSC="Nmea/Output","on"'; sleep 0.4		# normal output
+		echo 'AT^SGPSC="Power/Antenna","auto"'; sleep 0.4	# switch LNA to auto mode - will report +CME ERROR if already in auto mode
 		) | /root/femtocom $IF >&2  &
 		echo /dev/ttyUSB1
 		;;
