Letux: root: twl/volumed: remove hard-coded card names and use first as default
Signed-off-by: H. Nikolaus Schaller <hns@goldelico.com>

diff --git a/Letux/root/twl b/Letux/root/twl
--- a/Letux/root/twl
+++ b/Letux/root/twl
@@ -11,10 +11,15 @@ trap "exit 1" SIGHUP SIGINT SIGTERM
 [ -r /sys/firmware/devicetree/base/sound/ti,twl6040 ] || NOVOLUMED=yes
 
 MONO=false
+CARD="$($SCRIPTPATH/findsoundcard -a | head -1)"
 
 while [ "$1" ]
 do
         case "$1" in
+        "-c" )
+		shift
+		CARD="$1"
+		;;
         "-d" )
 		DEMO=yes
 		;;
@@ -39,6 +44,7 @@ do
 		;;
 	-* )
 		echo unknown option $1
+		echo "-c dev	device"
 		echo "-d	demo"
 		echo "-m	file is mono (1 channel) or take first channel only"
 		echo "-nv	no volumed"
@@ -56,19 +62,19 @@ do
 	shift
 done
 
+NUM=$($SCRIPTPATH/findsoundcard "$CARD")
+if [ ! "$NUM" ]
+then
+	echo sound card "$CARD" not found >&2
+	exit
+fi
+
+# FIXME: make this all depend on presence of amixer controls
+
 if [ -r /sys/firmware/devicetree/base/sound/ti,twl6040 ]
 then
 
 echo "TWL6040 (Pandaboard, OMAP5432EVM, Pyra, ...)"
-CARD=L15	# I have no idea where this "L15" is defined in the kernel
-		# but this is what aplay -L reports
-NUM=$($SCRIPTPATH/findsoundcard "$CARD")
-
-if ! [ "$NUM" ]
-then
-	CARD="PandaBoardES"
-	NUM=$($SCRIPTPATH/findsoundcard "$CARD")
-fi
 
 amixer -c "$NUM" -q set "Aux FM" 0% || exit
 amixer -c "$NUM" -q set "Capture" 100% || exit
@@ -96,9 +102,9 @@ if [ ! "$NOVOLUMED" ] # start volumed
 then
 if [ "$NOHANDSFREE" ]
 then
-	$SCRIPTPATH/volumed -q -nhf &
+	$SCRIPTPATH/volumed -c "$CARD" -q -nhf &
 else
-	$SCRIPTPATH/volumed -q &
+	$SCRIPTPATH/volumed -c "$CARD" -q &
 fi
 fi
 
@@ -127,7 +133,6 @@ REMIX_STEREO="remix 1 2 1 2"
 else
 
 echo "TWL4030 (GTA04, ...)"
-CARD=gta04
 NUM=$($SCRIPTPATH/findsoundcard "$CARD")
 
 amixer -c "$NUM" -q set "AVADC Clock Priority" "HiFi high priority" || exit
diff --git a/Letux/root/volumed b/Letux/root/volumed
--- a/Letux/root/volumed
+++ b/Letux/root/volumed
@@ -3,31 +3,44 @@
 # Pyra volume control daemon
 #
 SCRIPTPATH="$(dirname "$0")"
+
+case "$(cat /proc/device-tree/model)" in
+	Pyra-* | LC15-EVM* )	# only Pyra and LC15EVM have a potentiometer connected to the GPADC
+		;;
+	* )
+		exit 1
+		;;
+esac
+
 GPADC=$($SCRIPTPATH/findiio "palmas-gpadc")
-NUM=$($SCRIPTPATH/findsoundcard "L15")	# twl6040 on Pyra
+CARD="$($SCRIPTPATH/findsoundcard -a | head -1)"
 
 if [ ! "GPADC" ]
 then
 	echo no volume wheel found >&2
 	exit
 fi
-if [ ! "$NUM" ]
-then
-	echo no sound card found >&2
-	exit
-fi
-
 LASTVOL="unknown"
 MAXWHEEL=1200	# reports 0..1250 mV but leave some margin
 
 while [ "$1" ]
 do
-        case "$1" in
-        "-q" )
+	case "$1" in
+	"-c" )
+		shift
+		CARD="$1"
+		;;
+	"-q" )
 		QUIET=true
 		;;
         "-nhf" )
 		NOHANDSFREE=yes
+		;;
+	-* )
+		echo unknown option $1
+		echo "-c dev	device"
+		echo "-q	quiet"
+		exit 1
 		;;
 	* )
 		break
@@ -36,7 +49,14 @@ do
 	shift
 done
 
-while true
+NUM=$($SCRIPTPATH/findsoundcard "$CARD")
+if [ ! "$NUM" ]
+then
+	echo sound card "$CARD" not found >&2
+	exit
+fi
+
+while true	# run as daemon in background
 do
 	WHEEL=$(cat $GPADC/in_voltage2_input 2>/dev/null)
 	# could apply non-linear scale for more intuitive control
